server:
  port: 6969

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format:
          sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pungu_store
    username:
    password:



# Spring Security configuration
logging:
  level:
    org:
      springframework:
        security: DEBUG


